import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import GrayBackground from "../../components/GrayBackground";
import Header from "../../components/Header";
import { SetType } from "../../types";
import prismaClient from "../../util/prismaclient";
import Image from "next/image";

//SwiperJS Stuff
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { EffectCards } from "swiper";
SwiperCore.use([EffectCards]);

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-cards";
import StudyCard from "../../components/StudyCard";
import TabButton from "../../components/TabButton";
import TabMenu from "../../components/TabMenu";
import { useAuthContext } from "../../context/Auth";
import Button from "../../components/Button";
import axios from "axios";
import { useRouter } from "next/dist/client/router";
import React from "react";
import Link from "next/link";

interface SetSlugProps {
  set?: SetType;
}

const SetSlug: NextPage<SetSlugProps> = ({ set }) => {
  const { user } = useAuthContext();
  const route = useRouter();

  const handleDelete = async () => {
    const del = await axios.delete(`/api/set/delete`, {
      data: { id: set?.id },
    });
    if (del.status == 200) {
      route.push("/?action=delete");
    }
  };

  return (
    <div>
      <Head>
        <title>Studify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GrayBackground />
      <Header />
      <div className="px-9">
        <h1 className="text-lg font-medium mb-4">{set?.title}</h1>
        <div className="flex w-full justify-center space-x-4 mb-3">
          <TabButton>
            <Image
              alt="flashcard"
              src="/images/flashcard-icon.svg"
              width={25}
              height={25}
            />
            <span>Flashcards</span>
          </TabButton>

          <TabButton>
            <Image
              alt="Learn"
              src="/images/learning-icon.svg"
              width={25}
              height={25}
            />
            <span>Learn</span>
          </TabButton>
        </div>
        {user?.id == set?.creatorId ? (
          <div className="flex justify-center space-x-4">
            <Button
              onClick={handleDelete}
              className="flex bg-accent-500 hover:bg-accent-600 rounded-lg text-black px-6 py-2  mb-3"
            >
              Delete
            </Button>
            <Link href={`/set/edit/${set?.id}`} passHref>
              <a className="flex bg-primary-500 rounded-lg text-white px-6 py-2  mb-3">
                Edit
              </a>
            </Link>
          </div>
        ) : (
          <></>
        )}

        <div className="w-[calc(100%-6rem)] mx-auto max-w-[430px] h-[300px] items-center justify-center shadow-xl">
          <Swiper effect="cards" grabCursor={true} className="rounded-lg">
            {set?.card?.map((cardValue) => {
              return (
                <SwiperSlide
                  className="flex items-center h-full w-full justify-center rounded-lg"
                  key={cardValue.id}
                >
                  <StudyCard key={cardValue.id} card={cardValue} />
                </SwiperSlide>
              );
            })}
          </Swiper>
        </div>
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const slug = query.slug as string;

  const set = await prismaClient.set.findUnique({
    where: { id: slug },
    select: {
      description: true,
      id: true,
      title: true,
      creatorId: true,
      card: { orderBy: { order: "asc" } },
    },
  });

  return { props: { set } };
};

export default SetSlug;
