import { NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import "react-toastify/dist/ReactToastify.css";
import { toast, ToastContainer } from "react-toastify";
import GrayBackground from "../../components/GrayBackground";
import Header from "../../components/Header";
import { useAuthContext } from "../../context/Auth";
import { useEffect } from "react";
import { TextField } from "../../components/TextField";

const CreateSet: NextPage = () => {
  const { user } = useAuthContext();
  const router = useRouter();
  useEffect(() => {
    if (!user) {
      toast.warn("💥 you must be logged in");
      setTimeout(() => {
        router.push("/");
      }, 2000);
    }

    return () => {};
  }, []);

  return (
    <div>
      <Head>
        <title>Studify | Create a Set</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="top-center" autoClose={1800} />
      <GrayBackground />
      <Header />
      <form className="px-9 mt-4 flex flex-col space-y-6">
        <div className="flex space-x-4 md:space-x-12">
          <TextField
            className="text-lg md:text-3xl"
            label="Title"
            placeholder="Study Set Title"
          />
          <TextField
            className="text-lg md:text-3xl"
            label="Description"
            placeholder="Description"
          />
        </div>
        <div className="w-full h-28 bg-white shadow-md" />
      </form>
    </div>
  );
};

export default CreateSet;
