import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import GrayBackground from "../components/GrayBackground";
import Header from "../components/Header";

const PageNotFound: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Studify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GrayBackground />
      <Header />
      <div className="h-screen w-full flex flex-col text-center  items-center justify-center">
        <h1 className="text-9xl">🤷‍♀️</h1>
        <h1 className="text-7xl  font-semibold">Page Not Found</h1>
      </div>
    </div>
  );
};

export default PageNotFound;
