import { NextPage } from "next";
import Head from "next/head";

const Library: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Studify | Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Library;
